apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "com.akylas.enforcedoze"
    def useExternalSigning = project.hasProperty('useExternalSigning')
    compileSdkVersion 36

    buildFeatures {
        buildConfig = true
        aidl = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        applicationId "com.akylas.enforcedoze"
        minSdkVersion 23
        targetSdkVersion 36
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        versionCode 90
        versionName "1.11.3-dev"
    }
    if (useExternalSigning) {
        signingConfigs {
            release {
                storeFile file(System.getenv("RELEASE_KEYSTORE"))
                storePassword System.getenv("RELEASE_KEYSTORE_PASSWORD")
                keyAlias System.getenv("RELEASE_KEYSTORE_ALIAS")
                keyPassword System.getenv("RELEASE_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            vcsInfo.include false
            if (useExternalSigning) {
                signingConfig signingConfigs.release
            }
            multiDexEnabled true
            minifyEnabled true
            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}

configurations.all {
    exclude group: 'com.android.support', module: 'support-v13'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.browser:browser:1.8.0'
//    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:core:1.6.1'
    
    // Shizuku
    def shizukuVersion = '13.1.5'
    implementation "dev.rikka.shizuku:api:$shizukuVersion"
    implementation "dev.rikka.shizuku:provider:$shizukuVersion"

//    def libsuVersion = '6.0.0'

    // The core module that provides APIs to a shell
//    implementation "com.github.topjohnwu.libsu:core:${libsuVersion}"

    // Optional: APIs for creating root services. Depends on ":core"
//    implementation "com.github.topjohnwu.libsu:service:${libsuVersion}"

    // Optional: Provides remote file system support
//    implementation "com.github.topjohnwu.libsu:nio:${libsuVersion}"
}
